feat: create profile view
PlatziMaster/master-platform-ant-ui pull request #11
Opened 2021-09-05 21:21 UTC by jbarriospd

- Maquetacion de la vista de perfiles
- se añade traducciones
- se añade datos fake con React Query
- configuración de editor para type = single quote

Estoy atento a tus comentarios @nicobytes.

2021-09-08 22:34 UTC, nicobytes requested changes

2021-09-08 22:34 UTC, nicobytes commented on src/services/infoUser.services.js
> +const mockData = [
@jbarriospd El mock de obtener un perfil no debería ser un array, ya que es la información de un solo usuario y no se renderiza varios.

Y el nombre del servicio podríamos cambiarlo a `profile.service.js`, ya que el endpoint final es `/v1/profile`

2021-09-08 22:34 UTC, nicobytes commented on src/components/pages/profile.page.js
> +          data.map((item) => <Profile key={item.id} {...item} />)
@jbarriospd No debería ser un array sino directamente un obj.

2021-09-08 22:34 UTC, nicobytes commented on src/App.js
> +import './translations/i18n';
@jbarriospd deberíamos dejar esto en el index.js

2021-09-08 22:34 UTC, nicobytes commented on src/services/infoUser.services.js
> +    coaches: {
@jbarriospd los coaches son un array y hay un campo llamado `type` para saber si es un Tp Coach o Ac Coach

2021-09-08 22:37 UTC, nicobytes commented
Hola @jbarriospd probando la UI vi que cuando se sube un archivo se rompe la UI.
![image](https://user-images.githubusercontent.com/7611944/132594682-bda576e2-0262-4f44-81c8-53643519167e.png)

Igualmente el propósito es del botón de upload subí un archivo de inmediato no una lista de archivos, pero eso lo podemos resolver en otro PR. 

2021-09-08 22:48 UTC, nicobytes commented
@jbarriospd llevando tu propuesta de usar la card te parece si lo manejamos de esta manera?

![image](https://user-images.githubusercontent.com/7611944/132595276-47e6e92c-2bb3-459b-a8e4-394c92b3da71.png)

Los iconos en el perfil serían:
- Platzi Profile
- Portafolio
- GitHub
- Linkend
- Descargar CV

Podríamos manejar la regla de Ant Desing [Keep it Lightweight](https://ant.design/docs/spec/lightweight#Toggle-Reveal-Tools)

![image](https://user-images.githubusercontent.com/7611944/132595580-92ff4428-3008-4110-8a67-65add05abc1e.png)


Y cada uno de estos campos se pueda editar.

2021-09-22 20:00 UTC, jbarriospd commented
@nicobytes Te dejo las correcciones, solo no entendi como aplicar el prinicipio Keep it Lightweight, pues todos los campos son traidos por la api.
Saludos

2021-09-22 22:31 UTC, nicobytes approved these changes

2021-09-22 22:31 UTC, merged