feat: create calendar view
PlatziMaster/master-platform-ant-ui pull request #9
Opened 2021-08-28 18:30 UTC by devacran

-Maquetacion de la vista de calendario 

Se añade la ruta `/calendar` y se maqueta la vista de`calendario`

![](https://user-images.githubusercontent.com/7611944/130537171-8868d2fd-718f-43a3-9d14-a214238046a8.png)

Fix #2

2021-08-31 02:08 UTC, nicobytes requested changes

2021-08-31 02:08 UTC, nicobytes commented on src/components/molecules/CalendarListItem.molecule.js
> +import { Button, Typography, Row, Col, Avatar, Space, Image } from "antd";
No se esta usando Image.

2021-08-31 02:08 UTC, nicobytes commented on src/components/pages/calendar.page.js
> +import "./demo.css";
Debería tener su propio archivo de estilos como calendar.css

2021-08-31 02:08 UTC, nicobytes commented on src/components/pages/calendar.page.js
> +  const mockData = [
Genial implementación de Mock data, sería bueno de una vez manejar estados de como obtener la data y traer ese como desde [React Query.](https://github.com/PlatziMaster/master-platform-ant-ui/blob/master/src/services/todos.service.js)

Podrías hacer un servicio nuevo algo como `events.service.js` y allí poner ese mock

Un ejemplo:
```js
export const stateEvents = 'events';
export function GetEvents() {
  return useQuery([stateEvents ], () => {
    return mockData;
  });
}
```

2021-08-31 02:08 UTC, nicobytes commented on src/components/molecules/CalendarListItem.molecule.js
> +            JOIN A SESSION
Se debe usar las traducciones.

2021-08-31 02:08 UTC, nicobytes commented on src/components/molecules/CalendarListItem.molecule.js
> +          <Button type="primary">ADD TO CALENDAR</Button>
Se debe usar las traducciones.

2021-08-31 02:08 UTC, nicobytes commented on src/components/pages/calendar.page.js
> +      <Title level={3}>This Week</Title>
Se debe usar las traducciones.

2021-08-31 02:14 UTC, nicobytes commented
¡Hola!

En general con respecto a componentes cumple con la función, sin embargo tengo las siguientes observaciones:

- El avatar no es alineado con el texto
- Los botones de acción no cumplen la regla de contraste que propone Ant Desing

> In order to help user make a quick operation (something like the form, modal), a more important operation or a operation with higher frequency would be emphasized. Ref => https://ant.design/docs/spec/contrast

![Group 2](https://user-images.githubusercontent.com/7611944/131430305-76897a1d-4bfa-4a90-8a8d-b2de0853ae2e.png)

Podríamos usar el componente de [List ](https://ant.design/components/list/)que tiene este caso de uso, imágenes, contenido, alineamiento y acciones.

![image](https://user-images.githubusercontent.com/7611944/131430610-b4f039dc-3d34-4959-9ac4-1eb97963fbad.png)

2021-09-03 20:37 UTC, devacran commented
> ¡Hola!
> 
> En general con respecto a componentes cumple con la función, sin embargo tengo las siguientes observaciones:
> 
> * El avatar no es alineado con el texto
> * Los botones de acción no cumplen la regla de contraste que propone Ant Desing
> 
> > In order to help user make a quick operation (something like the form, modal), a more important operation or a operation with higher frequency would be emphasized. Ref => https://ant.design/docs/spec/contrast
> 
> ![Group 2](https://user-images.githubusercontent.com/7611944/131430305-76897a1d-4bfa-4a90-8a8d-b2de0853ae2e.png)
> 
> Podríamos usar el componente de [List ](https://ant.design/components/list/)que tiene este caso de uso, imágenes, contenido, alineamiento y acciones.
> 
> ![image](https://user-images.githubusercontent.com/7611944/131430610-b4f039dc-3d34-4959-9ac4-1eb97963fbad.png)

@nicobytes Listo nico, añadi el componente de lista. Aunque me fije que los avatar, en el componente de lista estan alineados arriba. Los dejo asi o deberian ir alineados al centro?

2021-09-03 23:41 UTC, nicobytes requested changes

2021-09-03 23:41 UTC, nicobytes commented on src/components/molecules/CalendarListItem.molecule.js
> +    <List.Item>
La API de la lista tiene una opción para manejar las acciones, usemos esa ya que se puede adaptar cuando uno le cambia el `itemLayout`, sería así:

```js
 <List.Item actions={[
      <Button type="primary">{t("master.Calendar.joinbtn")}</Button>,
      <Button type="secondary">{t("master.Calendar.addbtn")}</Button>,
    ]}>
```

https://ant.design/components/list/#API

2021-09-03 23:41 UTC, nicobytes commented on src/components/pages/calendar.page.js
> +        {isLoading ? (
La Api de List ya tiene un estado de loading entonces nos ahorramos ese código.

```js
<List
          dataSource={data}
          loading={isLoading}
          renderItem={(item) => <CalendarListItem {...item} />}
        />
```
https://ant.design/components/list/#API

2021-09-03 23:44 UTC, nicobytes commented
Hola! @devacran gran trabajo esta quedando genial, algo que se me olvido decir es que debemos usar `PropTypes`, en los componentes que reciben props.

Ejemplo:

```js
import PropTypes from 'prop-types';

function Greeting ({name}) {
    return (
      <h1>Hello, {name}</h1>
    );
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

2021-09-05 21:52 UTC, devacran commented on src/components/molecules/CalendarListItem.molecule.js
> +    <List.Item>
Gracias! no me habia dado cuenta que se podia hacer eso jeje

2021-09-05 21:53 UTC, devacran commented on src/components/pages/calendar.page.js
> +        {isLoading ? (
> Hola! @devacran gran trabajo esta quedando genial, algo que se me olvido decir es que debemos usar `PropTypes`, en los componentes que reciben props.
> 
> Ejemplo:
> 
> ```js
> import PropTypes from 'prop-types';
> 
> function Greeting ({name}) {
>     return (
>       <h1>Hello, {name}</h1>
>     );
> }
> 
> Greeting.propTypes = {
>   name: PropTypes.string
> };
> ```

@nicobytes Ya se añadieron proptypes y se corrigio el componete de lista :)

2021-09-08 23:19 UTC, nicobytes approved these changes

2021-09-08 23:19 UTC, merged